### ISSUE TITLE
Failure indexing 'long' documents

### ISSUE THREAD

**Issue by ajrnz** [outr/lucene4s#10]
If I run the following 

```scala
import $ivy.`com.outr::lucene4s:1.8.1`
import com.outr.lucene4s._

val lucene = new com.outr.lucene4s.DirectLucene(Nil)
val longString = "puzzling " * (32768/8)
println(longString.length)
val textField = lucene.create.field[String]("text")
lucene.doc().fields(textField(longString)).index()
```

I get

```
java.lang.IllegalArgumentException: DocValuesField "text" is too large, must be <= 32766
  org.apache.lucene.index.SortedDocValuesWriter.addValue(SortedDocValuesWriter.java:73)
  org.apache.lucene.index.DefaultIndexingChain.indexDocValue(DefaultIndexingChain.java:552)
  org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:465)
  org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:392)
  org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:251)
  org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:494)
  org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1602)
  org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1221)
  com.outr.lucene4s.document.DocumentBuilder.index(DocumentBuilder.scala:70)
  ammonite.$file.example$.<init>(example.sc:8)
  ammonite.$file.example$.<clinit>(example.sc)
```

How do I avoid this? (It also happens with the `fullText` field). It looks like I need to disable DocValues for this field? But I can't figure out how to make this work

**Comment by darkfrog26** [comment]
Looks like it's a limitation of sorting fields. Surprisingly, I've never seen that before.  It should be possible to fix this by auto-truncating the sort field generated since l4s generates multiple indexed fields for each field. Would you be interested in creating a PR for this?

**Comment by ajrnz** [comment]
My Lucene knowledge is pretty limited. Could you point me to where these fields are being generated? (I really don't care about sorting on these fields and would prefer to turn it off)

**Comment by darkfrog26** [comment]
I believe this is the place in the code where it's going awry: https://github.com/outr/lucene4s/blob/master/src/main/scala/com/outr/lucene4s/field/value/support/StringValueSupport.scala#L13

**Comment by ajrnz** [comment]
Thanks. Truncating isn't a great option as it's hard to decide the amount of truncation as the byte array has a max size. A significantly smaller (say Chinese) string could still case an overflow. (I guess you could truncate iteratively but that feels ugly as well. I doubt you would ever want to sort on string this long anyway. I have a PR for disabling sorting for a field.
