### ISSUE TITLE
boosting

### ISSUE THREAD

**Issue by bogorman** [outr/lucene4s#2]
I am using the Searchable trait to automatically index my case class and that works well. I need to boost one of the fields on the case class as it has more importance to the search results. I don't see a way of doing that. Is there a way I can get to the raw lucene field and call setBoost on it?

**Comment by darkfrog26** [comment]
I used to have this functionality, but I haven't been using boost in quite a while so I think in the latest version it must have just fallen out during a refactor.  If you'd be interested in submitting a PR it would be welcome.  Otherwise, I'll try to get it added in the near future.  Do you have any specifics of what you'd like to see?

**Comment by darkfrog26** [comment]
Ah, I believe this was the reason it was removed: https://issues.apache.org/jira/browse/LUCENE-6819

Sorry, I've slept since the last re-write and Lucene is complex beast.  I wrote this library to avoid the complexities in my projects so I do my best to block it out after it's working. ;)

**Comment by darkfrog26** [comment]
If I recall, the best way to support this is boosting the query instead of the field.

**Comment by bogorman** [comment]
I am ok with using boost in the query also. Do you have an example of how to do that? I am doing a wildcard query and trying to boost one field to have more importance if the match is on that field. From reading around I see wildcard and boost are not compatible either. 

for e.g
case class SearchItem(title: String, keyword1: String,keyword2:String)

So in my data I can have the same text in the title and in the keywords but spread over many entries. Any matches on the title should score much higher than the keywords. I'm doing a wildcard search. So how would I boost the title entries in this case? Thanks for the help.

**Comment by darkfrog26** [comment]
The easiest way is just to do something like this:

`lucene.query().filter(parse("title:term^4")).search()`
