### ISSUE TITLE
Will Searchable return?

### ISSUE THREAD

**Issue by barryoneill** [outr/lucene4s#26]
Hi! The README refers to a `Searchable` interface that seems to have been quietly removed in 1.11.  Is it coming back?

**Comment by darkfrog26** [comment]
Unfortunately, it was removed during the migration to Scala 3 because of its use of Macros and was never revisited. The code is still there, just commented out if you'd like to provide a Scala 3 version. Alternatively, you're welcome to submit a PR that supports it only on Scala 2.x if you'd like.

**Comment by barryoneill** [comment]
I understand, thanks for the response.  TBH publishing for just 2.x is the same as not upgrading, so I'll probably just stay on this version until I get as far as moving all my stuff to scala 3 anyway :)

Thanks!

**Comment by darkfrog26** [comment]
Fair enough. I don't have any projects I'm currently working on using lucene4s, but that's likely to change in the near future. When that happens I'll probably come back and do some cleanup, upgrades, and give it some TLC.

**Comment by barryoneill** [comment]
No worries, and thank you again for this library!
