### ISSUE TITLE
custom stopwords

### ISSUE THREAD

**Issue by bogorman** [outr/lucene4s#3]
Is there a way to customise the stopwords. I see the StandardAnalyzer is created with no params so it will default to the standard set of stop words and I have no way to change that.

**Comment by darkfrog26** [comment]
When you instantiate `KeywordIndexing` you can provide a custom `stopWords: Set[String]`.

**Comment by darkfrog26** [comment]
Ah, sorry, I misunderstood what you were referring to.  That's a good point.  If you'd like to submit a PR that adds support to `Lucene` to take a custom `stopWords` list I'll be happy to merge it in.

**Comment by bogorman** [comment]
OK. For the moment I have just created a custom lucene version which works for what I need but it would be cleaner to have it as a constructor param. 

`class CustomLucene() extends Lucene(defaultFullTextSearchable = true, directory = None) {
  override lazy val standardAnalyzer = new StandardAnalyzer(CharArraySet.EMPTY_SET)
}`

**Comment by darkfrog26** [comment]
Give me a couple minutes, this is actually an easy update. :)

**Comment by darkfrog26** [comment]
Take a look at that commit. Does it fulfill your needs completely?

**Comment by darkfrog26** [comment]
@bogorman please let me know if the commit I made resolves your issue and I'll do another release.

**Comment by bogorman** [comment]
looks good. thanks.
