### ISSUE TITLE
Loading and modifying existing index

### ISSUE THREAD

**Issue by fahadkh** [outr/lucene4s#6]
Scala version: 2.12, lucene4s version: 1.8.3

I may be misunderstanding, but the appendIfExists = true parameter to DirectLucene should allow me to load and modify an existing index on disk (CREATE_OR_APPEND). However, the index on disk is wiped out after the program restarts and tries to load the index:

1. Create Index: 
```
val directoryMain: Path = Paths.get("lucene_index")
val luceneCreation = new DirectLucene(uniqueFields = List("pk_id"), directory = Option(directoryMain), appendIfExists = true, defaultFullTextSearchable = true)
val lucene: SearchableData = luceneCreation.create.searchable[SearchableData]

val searchDataList = /* index data */
searchDataList.foreach(searchData => lucene.insert(searchData).index())
```

2. Close program and restart:
```
val directoryMain: Path = Paths.get("lucene_index")
val luceneCreation = new DirectLucene(uniqueFields = List("pk_id"), directory = Option(directoryMain), appendIfExists = true, defaultFullTextSearchable = true)
val lucene: SearchableData = luceneCreation.create.searchable[SearchableData]
```

3. Query data (or add new data) - this causes index to be wiped out:
```
lucene.query().sort(Sort.Score).filter(parse(s"$searchTerm", allowLeadingWildcard = true)).limit(100).search().entries.toList
```

I was hoping for a way to persist the index between runs. Please let me know if this is even possible and if I am attempting it correctly. Thanks!

**Comment by darkfrog26** [comment]
My guess is that `directoryMain` is null, so it's creating an in-memory index.  I use persistent indexes for everything but tests, so lucene4s has been well tested for the functionality. ;)

**Comment by fahadkh** [comment]
Interesting - I tried accessing some methods of directoryMain and was able to get the folder name/filesystem so it doesn't seem like its null. The folder also gets populated with the index files after creating the index.

Do you by any chance have any examples of loading a persistent index and querying it?

Thanks!

**Comment by darkfrog26** [comment]
Try making sure to `commit()` manually before you let the application terminate. It's possible that you're letting the application terminate before the background flushing occurs.

**Comment by fahadkh** [comment]
That seems to have done the trick for persisting the index:

```
val directoryMain: Path = Paths.get("lucene_index")
val luceneCreation = new DirectLucene(uniqueFields = List("pk_id"), directory = Option(directoryMain), appendIfExists = true, defaultFullTextSearchable = true)
val lucene: SearchableData = luceneCreation.create.searchable[SearchableData]

val searchDataList = /* index data */
searchDataList.foreach(searchData => lucene.insert(searchData).index())
luceneCreation.commit()
```

Weirdly enough, I let the service run for a while and it still would not persist until I added in the commit() manually.

Thanks

**Comment by darkfrog26** [comment]
@fahadkh sorry, I was misremembering. In Lucene, you need to always manually commit things.  You can turn on `autoCommit` if your load is low enough and don't want to worry about remembering, but for high performance, you should do all of your updates in batch and then call commit when you're done.

**Comment by fahadkh** [comment]
Makes sense, thank you for the help!
