### ISSUE TITLE
Incorrect results after updating documents

### ISSUE THREAD

**Issue by hajime-moto** [outr/lucene4s#9]
@darkfrog26 I'm writing some stress tests and I'm seeing incorrect results being returned after a document is updated.

Here is my test which passes sometimes and fails sometimes. I'm not sure what this is happening but if you run this multiple times it should fail eventually.

This test 
- creates UUID tokens (session tokens) for each email. 
- updated all tokens to be expired and adds a new field `sessionExpireField` which sets the expiry time.
- searches each token to assert that all documents have `sessionExpireField` set. 

I've added the failure I'm seeing in the comment.

```scala

import java.util.UUID

import org.scalatest.concurrent.Eventually
import org.scalatest.{Matchers, WordSpec}

import scala.util.Try

class LuceneTokenSpec extends WordSpec with Matchers with Eventually {

  import com.outr.lucene4s._
  import com.outr.lucene4s.field.{Field, FieldType}

  val lucene: Lucene = new DirectLucene(uniqueFields = List.empty, defaultFullTextSearchable = true, autoCommit = true)

  val sessionTokenField: Field[String] = lucene.create.field[String](name = "sessionTokenField", FieldType.Untokenized)
  val sessionEmailField: Field[String] = lucene.create.field[String](name = "sessionEmailField")
  val sessionExpireField: Field[Long] = lucene.create.field[Long](name = "sessionExpireField")

  "generate session tokens for emails, expire tokens and assert that expire time is set" in {
    val userEmails = (1 to 1000) map (i => s"email$i@email.com")

    //generate token tokens for each email and persist
    val tokensAndEmails =
      userEmails map {
        email =>
          val token = UUID.randomUUID().toString
          lucene.doc().fields(sessionTokenField(token), sessionEmailField(email)).index()
          (token, email)
      }

    //update all tokens to be expired
    tokensAndEmails foreach {
      case (token, email) =>
        lucene
          .update(sessionTokenField(token))
          .fields(
            sessionTokenField(token),
            sessionEmailField(email),
            sessionExpireField(System.currentTimeMillis())
          ).index()
    }

    //fetch each token and assert that expired field is set
    tokensAndEmails foreach {
      case (token, email) =>
        val results = lucene.query().filter(sessionTokenField(token)).search().results
        results should have size 1
        val headResult = results.head

        /**
          * "[3e02ad85-ae9c-4de5-a5ec-ba11c3362dba]" was not equal to "[def49e07-d44b-4374-a78b-732c53f10557]"
          * ScalaTestFailureLocation: LuceneTokenSpec at (LuceneTokenSpec.scala:48)
          * Expected :"[def49e07-d44b-4374-a78b-732c53f10557]"
          * Actual   :"[3e02ad85-ae9c-4de5-a5ec-ba11c3362dba]"
          *
          * "[f33ffbeb-0eec-483e-9a0a-26b1aa95f09a]" was not equal to "[75751106-58f5-438a-af4a-dcd0156b769e]"
          * ScalaTestFailureLocation: LuceneTokenSpec at (LuceneTokenSpec.scala:58)
          * Expected :"[75751106-58f5-438a-af4a-dcd0156b769e]"
          * Actual   :"[f33ffbeb-0eec-483e-9a0a-26b1aa95f09a]"
          */
        headResult(sessionTokenField) shouldBe token
        headResult(sessionEmailField) shouldBe email
        Try(headResult(sessionExpireField)).toOption shouldBe defined
    }
  }
}
```

**Comment by darkfrog26** [comment]
Make sure to call `commit()` before trying to query anything back.

**Comment by darkfrog26** [comment]
I would also recommend staying away from `autoCommit` as it has some serious performance penalties that can creep up on you.

**Comment by darkfrog26** [comment]
Also, I'd really recommend investigating the case class support as it simplifies things quite a bit.

**Comment by hajime-moto** [comment]
Gotcha. Will look at case class support. But it's funny that it's returning incorrect session token. I'm guessing it's a Lucene issue.

**Comment by darkfrog26** [comment]
Try adding the `commit()` and see if that changes things

**Comment by darkfrog26** [comment]
@hajime-moto, any updates on this?

**Comment by hajime-moto** [comment]
Sorry for the late reply. I tried `commit()` after every write but the problem still exists :( ...May be it's a Lucene thing. Not sure where the problem was occurring by the above test was failing. I ended up using Postgres instead.

**Comment by darkfrog26** [comment]
I'll try to get a look at this when I have some time and let you know. Sorry, you had to use Postgres' crappy search functionality. ;)

**Comment by hajime-moto** [comment]
Yep wish I didn't have to use Postgres either :( This library is super amazing! Got me up and running with a few seconds. Postgres and slick integration took much longer and configuring thread polling with HikariCP was no fun :(

Yep totally agree Lucene's search is way better.

**Comment by darkfrog26** [comment]
Okay, I finally got a chance to look at this. I was able to get it to work with this code: https://github.com/outr/lucene4s/blob/master/src/test/scala/tests/TokenSpec.scala#L45

A couple changes:
1.) Removal of dashes. For some reason, the Lucene parser doesn't like dashes that aren't properly escaped. Since you're using UUIDs the dashes are just wasting space anyway. However, if you wanted the dashes stored you could always escape them. I went the simpler route.
2.) While I have not been able to determine what difference there is between the `TermQuery` that the query parser creates and the one lucene4s generates, it must be somehow different because using the parser to generate it works consistently while creating it manually does not.  I need to look into this further though because it's very strange.

I almost never do exact match queries in Lucene because that's what a database is for.  Lucene is designed to be coupled with a database to offer indexing and searching for more advanced queries.

**Comment by hajime-moto** [comment]
That's awesome. Thank you so much. I'm stuck with Postgres and Slick for a few months :(

**Comment by darkfrog26** [comment]
Slick is awful. You might want to consider my SQL library http://scalarelational.org
